In [ ]:
# Problem - 1: Array creation:
"""
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
"""

# 1.
import numpy as np;
empty_array = np.zeros((2, 2))
empty_array

array([[0., 0.],
       [0., 0.]])

In [ ]:
# 2.
import numpy as np;
one_array = np.ones((4, 2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# 3.
import numpy as np;
new_array = np.full((4, 2), fill_value = 111)
print("Array with given shape and type: ")
new_array


Array with given shape and type: 


array([[111, 111],
       [111, 111],
       [111, 111],
       [111, 111]])

In [ ]:
# 4.
import numpy as np
first_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
new_array = np.zeros_like(first_array)
print(new_array)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# 5.
import numpy as np
first_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
new_array = np.ones_like(first_array)
print(new_array)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
# 6.
import numpy as np
new_list = [1, 2, 3, 4]
convert_list = np.array(new_list)
convert_list

array([1, 2, 3, 4])

In [ ]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
"""
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.
"""

# 1.
import numpy as np
array_one = np.arange(10, 49)
array_one

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
# 2.
import numpy as np
array_two = np.arange(9).reshape(3, 3)
array_two

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 3.
import numpy as np
array_three = np.eye(3)
array_three

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 4.
import numpy as np
array_four = np.random.random(30)
array_four
array_four = np.mean(array_four)
array_four

0.4859590821183541

In [ ]:
# 5.
import numpy as np
array_five = np.random.rand(10, 10), np.max, np.min
array_five

(array([[0.84961943, 0.74313904, 0.85347023, 0.22564101, 0.79224943,
         0.92183385, 0.38577396, 0.33163157, 0.62648738, 0.8748379 ],
        [0.79335241, 0.3335873 , 0.10665099, 0.56280567, 0.83437503,
         0.92039846, 0.61225155, 0.110106  , 0.23392318, 0.21785043],
        [0.88566851, 0.90023726, 0.67602786, 0.27573869, 0.25859523,
         0.41191703, 0.56912136, 0.36076623, 0.21943105, 0.09401092],
        [0.23709819, 0.01036073, 0.89696383, 0.44699748, 0.06438371,
         0.61956312, 0.89993764, 0.56891006, 0.22135331, 0.93550317],
        [0.10378597, 0.73864943, 0.7135975 , 0.68109952, 0.57317868,
         0.36827213, 0.65773571, 0.07733703, 0.73188268, 0.66587103],
        [0.48665269, 0.390446  , 0.58409149, 0.64486655, 0.85644654,
         0.16803601, 0.25206535, 0.7536677 , 0.89122056, 0.94082294],
        [0.87988172, 0.17088621, 0.42966856, 0.28532851, 0.53790852,
         0.06178926, 0.81409387, 0.74031517, 0.46394272, 0.47211333],
        [0.23200605, 0.1959

In [ ]:
# 6.
import numpy as np
six_array = np.zeros(10)
six_array

six_array[4] = 1
six_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
# 7.
import numpy as np
array = [1, 2, 0, 0, 4, 0]
seven_array = np.flip(array)
seven_array

array([0, 4, 0, 0, 2, 1])

In [ ]:
# 8.
import numpy as np
eight_array = np.ones((5, 5))
print("1 on the border and 0 inside the array:")
eight_array[1: -1, 1: - 1] = 0
(eight_array)

1 on the border and 0 inside the array:


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 9.
import numpy as np
nine_array = np.zeros((8, 7))

nine_array [::2, ::2] = 1
nine_array [::2, 1::2] = 1
nine_array

array([[1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
"""
Problem - 3: Array Operations:
         For the following arrays:
           x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
           v = np.array([9,10]) and w = np.array([11,12]);
             Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
"""

# 1.
import numpy as np
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9, 10])
w = np.array([11, 12])

one_array = np.add(x, y)
one_array

array([[ 6,  8],
       [10, 13]])

In [ ]:
# 2.
import numpy as np
two_array = np.subtract(x, y)
two_array

array([[-4, -4],
       [-4, -3]])

In [ ]:
# 3.
import numpy as np
three_array = np.multiply(3, x)
three_array

array([[ 3,  6],
       [ 9, 15]])

In [ ]:
# 4.
import numpy as np
square_1 = np.square(x)
square_1
square_2 = np.square(y)
square_2

array([[25, 36],
       [49, 64]])

In [ ]:
# 5.
import numpy as np
x = np.array([[1,2],[3,6]])
y = np.array([[5,6],[7,8]])
dot1 = np.dot(x,y)
print(dot1)

v = np.array([9, 10])
w = np.array([11,12])
dot2 = np.dot(v,w)
print(dot2)

dot3 = np.dot(x,v)
print(dot3)

[[19 22]
 [57 66]]
219
[29 87]


In [ ]:
# 6.
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])
concate_1 = np.concatenate((x,y), axis = 1)
print(concate_1)

concate_2 = np.concatenate((v,w), axis = 0)
print(concate_2)

[[1 2 5 6]
 [3 5 7 8]]
[ 9 10 11 12]


In [ ]:
# 7.
import numpy as np
concate_3 = np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
"""
Problem - 4: Matrix Operations:
             • For the following arrays:
               A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
                Prove following with Numpy:
                 1. Prove A.A−1 = I.
                 2. Prove AB ̸= BA.
                 3. Prove (AB)T = BTAT.


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}
"""

# 1. Prove A.A*^(−1) = I.
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inverse = np.linalg.inv(A)
check_identity = np.dot(A, A_inverse)
print("A * A^(-1) = I:")
print(check_identity)

A * A^(-1) = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
# 2. Prove AB ̸= BA.
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB != BA:")
print("AB:")
print(AB)
print("BA:")
print(BA)
print("AB and BA are equal?", np.array_equal(AB, BA))

AB != BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Are AB and BA equal? False


In [ ]:
# 3. Prove (AB)^T = B^T*A^T
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)

print("(AB)^T = B^T*A^T:")
print("(AB)^T:")
print(AB_transpose)
print("B^T*A^T:")
print(BT_AT)
print("(AB)^T and B^T * A^T are equal?", np.array_equal(AB_transpose, BT_AT))

(AB)^T = B^T*A^T:
(AB)^T:
[[23 51]
 [13 29]]
B^T*A^T:
[[23 51]
 [13 29]]
(AB)^T and B^T * A^T are equal? True


In [ ]:
"""
Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
"""

import numpy as np
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inverse = np.linalg.inv(A)
print("Inverse of A:\n", A_inverse)

X = np.dot(A_inverse, B)
print("Solution x:", np.linalg.solve(A, B))

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution x: [ 2.  1. -2.]
