• To - Do - 1:

1. Read and Observe the Dataset.
2. Print top(5) and bottom(5) of the dataset {Hint: pd.head and pd.tail}.
3. Print the Information of Datasets. {Hint: pd.info}.
4. Gather the Descriptive info about the Dataset. {Hint: pd.describe}
5. Split your data into Feature (X) and Label (Y).

In [48]:
import pandas as pd

In [49]:
# 1.
# read csv file
df = pd.read_csv('/content/drive/MyDrive/Concepts of technologies and AI/student.csv')

# observe the dataset
df

Math  Reading  Writing
0      48       68       63
1      62       81       72
2      79       80       78
3      76       83       79
4      59       64       62
..    ...      ...      ...
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

[1000 rows x 3 columns]

In [50]:
# 2.
# for top 5 of dataset
df = df.head(5)
df

Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [51]:
# for bottom 5 of dataset
df = df.tail(5)
df

Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [52]:
# 3.
# information of datasets
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     5 non-null      int64
 1   Reading  5 non-null      int64
 2   Writing  5 non-null      int64
dtypes: int64(3)
memory usage: 248.0 bytes


In [53]:
# 4.
# gathering descriptive information about dataset
df.describe()


Math   Reading    Writing
count   5.000000   5.00000   5.000000
mean   64.800000  75.20000  70.800000
std    12.755391   8.58487   8.043631
min    48.000000  64.00000  62.000000
25%    59.000000  68.00000  63.000000
50%    62.000000  80.00000  72.000000
75%    76.000000  81.00000  78.000000
max    79.000000  83.00000  79.000000

In [55]:
# 5.
# spliting data into Feature (X) and Label (Y).
X = df.iloc[:, :-1] # all columns except last one
Y = df.iloc[:, -1] # last column

print("Features (X): ")
print(X)
print("Label (Y): ")
print(Y)

Features (X): 
   Math  Reading
0    48       68
1    62       81
2    79       80
3    76       83
4    59       64
Label (Y): 
0    63
1    72
2    78
3    79
4    62
Name: Writing, dtype: int64


• To - Do - 2:
1. To make the task easier - let’s assume there is no bias or intercept.
2. Create the following matrices:

Y = WTX


W =





w1
w2
.
.
.
wd





, where W ∈ R
d

X =





x1,1 x1,2 · · · x1,n
x2,1 x2,2 · · · x2,n
.
.
.
.
.
.
.
.
.
.
.
.
xd,1 xd,2 · · · xd,n





, where X ∈ R
d×n

Y =





y1
y2
.
.
.
yn





, where Y ∈ R
n

3. Note: The feature matrix described above does not include a column of 1s, as it assumes the
absence of a bias term in the model.

In [56]:
import numpy as np
W = np.array([[2], [3], [4]])

X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

Y = np.dot(W.T, X)

print("Weight vector W:")
print(W)

print("\nFeature matrix X:")
print(X)

print("\nResulting vector Y:")
print(Y)

Weight vector W:
[[2]
 [3]
 [4]]

Feature matrix X:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Resulting vector Y:
[[ 64  73  82  91 100]]


• To - Do - 3:
1. Split the dataset into training and test sets.
2. You can use an 80-20 or 70-30 split, with 80% (or 70%) of the data used for training and the rest
for testing.

In [70]:
from sklearn.model_selection import train_test_split

target_column = 'Math'
X = df.drop(columns=[target_column])
Y = df[target_column]

print("X shape before splitting:", X.shape)
print("Y shape before splitting:", Y.shape)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Y_train shape:", Y_train.shape)
print("Y_test shape:", Y_test.shape)


X shape before splitting: (5, 2)
Y shape before splitting: (5,)
X_train shape: (4, 2)
X_test shape: (1, 2)
Y_train shape: (4,)
Y_test shape: (1,)


• To - Do:

We will define a function that:
1. Loads the data and splits it into training and test sets.
2. Prepares the feature matrix (X) and target vector (Y).
3. Defines the weight matrix (W) and initializes the learning rate and number of iterations.
4. Calls the gradient descent function to learn the parameters.
5. Evaluates the model using RMSE and R2

In [61]:
from sklearn.metrics import mean_squared_error, r2_score

In [66]:
def linear_regression_pipeline(file_path, target_column, learning_rate=0.01, iterations=1000):

    X = df.drop(columns=['Math']).values
    Y = df['Reading'].values.reshape(-1, 1)

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    m, n = X_train.shape
    W = np.zeros((n, 1))
    b = 0
    losses = []

    def gradient_descent(X, Y, W, b, learning_rate, iterations):
        m = X.shape[0]
        for i in range(iterations):

            Y_pred = np.dot(X, W) + b

            loss = np.mean((Y_pred - Y) ** 2)
            losses.append(loss)

            dW = (2 / m) * np.dot(X.T, (Y_pred - Y))
            db = (2 / m) * np.sum(Y_pred - Y)

            W -= learning_rate * dW
            b -= learning_rate * db

        return W, b, losses

    W, b, losses = gradient_descent(X_train, Y_train, W, b, learning_rate, iterations)

    Y_pred_test = np.dot(X_test, W) + b
    rmse = np.sqrt(mean_squared_error(Y_test, Y_pred_test))
    r2 = r2_score(Y_test, Y_pred_test)

    print("Model Evaluation:")
    print("RMSE:", rmse)
    print("R2 Score:", r2)

    return W, b, losses


In [69]:
# Main Function
def main():
# Step 1: Load the dataset
   df = pd.read_csv('/content/drive/MyDrive/Concepts of technologies and AI/student.csv')
# Step 2: Split the data into features (X) and target (Y)
   X = df[['Math', 'Reading']].values # Features: Math and Reading marks
   Y = df['Writing'].values # Target: Writing marks
# Step 3: Split the data into training and test sets (80% train, 20% test)
   X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
# Step 4: Initialize weights (W) to zeros, learning rate and number of iterations
   W = np.zeros(X_train.shape[1]) # Initialize weights
   alpha = 0.00001 # Learning rate
   iterations = 1000 # Number of iterations for gradient descent
# Step 5: Perform Gradient Descent
   W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)
# Step 6: Make predictions on the test set
   Y_pred = np.dot(X_test, W_optimal)
# Step 7: Evaluate the model using RMSE and R-Squared
   model_rmse = rmse(Y_test, Y_pred)
   model_r2 = r2(Y_test, Y_pred)
# Step 8: Output the results
   print("Final Weights:", W_optimal)
   print("Cost History (First 10 iterations):", cost_history[:10])
   print("RMSE on Test Set:", model_rmse)
   print("R-Squared on Test Set:", model_r2)
# Execute the main function
   if __name__ == "__main__":
    main()